### ISSUE TITLE
Support contract upgradeability

### ISSUE THREAD

**Issue by terminator0x** [plexus-money/contracts#14]
**Problem**

Currently upgrading the `plexus` contracts to newer versions on the mainnet would require all liquidity and variables be manually transferred to the newly created contracts. The reason for this is that ethereum smart contracts by nature are immutable once deployed.

So not only will it be cumbersome to upgrade the current plexus contracts, but it'll also be very risky as liquidity in the contract can be lost during the migration and also vital contract state info i.e. user balances e.t.c

**Solution**

This issue can be solved by using [proxy registries and contracts](https://github.com/somish/govblocks-protocol/blob/npm/contracts/proxy/Proxy.sol) that call the newly deployed contracts that have the updated dApp logic using `delegatecalls`. 

In doing this, we abstract the logic from the main contracts which remain immutable and also we make sure that the overall state of plexus i.e. user token balances e.t.c is not tampered with every time we update the dApp logic and deploy new contracts.

**Acceptance Criteria**

One should be able to migrate the current plexus contracts to new addresses without loosing existing global state data and any liquidity in the main contracts.

Unit test cases should also be added to showcase this functionality once completed.

**ETA**

5 days

**Comment by terminator0x** [comment]
@softskillpro any updates?

**Comment by terminator0x** [comment]
@softskillpro just to clarify, these are the contracts that need to be upgrade-able

![121563562-319d7180-ca23-11eb-99c3-bcdcec42a668](https://user-images.githubusercontent.com/78132555/121729493-39c6e100-caf7-11eb-81c2-8dad33ae71d3.png)

**Comment by softskillpro** [comment]
These are what I worked on. 
https://github.com/plexus-money/contracts/pull/23

1. Update contracts with proxy.
- core.sol, oracle.sol, wrapper.sol, wrapperSushi.sol, tokenRewards.sol, tier1Staking.sol, tier2Farm.sol, tier2Aave.sol, tier2Pickle.sol are updated.  You can check following directory.
/contracts/proxyLib
- Note:
Contracts are based on OwnableUpgradeable contract and need variable initialization.
for example : we initialized global and init variables in initialize() instead of constructor() in Core.sol file.
```
function initialize() initializeOnceOnly public {
  burnaddress = address(0x0);
  uniswapAddress = 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D;
  uniswap = IUniswapV2RouterLite(uniswapAddress);
  usdcCoinAddress = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
}
```
2. Fix code convention issues base on Natspec format and official style guide.

**Comment by softskillpro** [comment]
A suggestion for the project.
Now all contract addresses are hard-coded in the source files, it looks bad.
We need to define all constant contract addresses in a single file, for ex, config.js, I think.

**Comment by terminator0x** [comment]
> A suggestion for the project.
> Now all contract addresses are hard-coded in the source files, it looks bad.
> We need to define all constant contract addresses in a single file, for ex, config.js, I think.

Thats ok @softskillpro , another dev is working on cleaning up the addresses and unused functions in #22. So they add the config too.

As for the contract upgrade-ability code, it looks awesome so far. We're currently sorting the Alchemy issue, so that we have the tests up & running again.

Also very importantly don't forget to add tests in hardhat for the contract upgrade functionality, they are necessary before I merge this issue and we move on to another task.
