### ISSUE TITLE
Document the solidity code and integrate `soldoc` to auto-generate the docs

### ISSUE THREAD

**Issue by terminator0x** [plexus-money/contracts#17]
Comment all the solidity code in all the files using the [NatSpec format](https://docs.soliditylang.org/en/v0.5.10/natspec-format.html).

Doing this will help the code be more understandable to other devs looking at the code.

Also add a script in the `scripts` folder that will use [soldoc](https://github.com/HQ20/soldoc) to generate plexus docs from the comments you have added.

We'll use this script to generate and deploy plexus documentation on the fly for ease of integration of the contracts with other systems.

**Comment by terminator0x** [comment]
@ruvaag I think it's better if you make a new PR for this, I've closed the old one, because of the many merge conflicts.

**Comment by ruvaag** [comment]
@terminator0x I was going through the recent changes and I think most of the contracts now has NatSpec format coding. Is there something particular pending there? If not, I'll start work on the script that will use soldoc to generate docs from the current state of the repo.

**Comment by terminator0x** [comment]
> @terminator0x I was going through the recent changes and I think most of the contracts now have NatSpec format coding. Is there something particular pending there?
> If not, I'll start work on the script that will use soldoc to generate docs from the current state of the repo.
> To your second point – Sure, I'll open a new PR.

Not all contracts have the NatSpec comments, our main contract `WrapAndUnWrap.sol` for [example](https://github.com/plexus-money/contracts/blob/master/contracts/WrapAndUnWrap.sol) needs to be well commented using the[ NatSpec format.](https://docs.soliditylang.org/en/v0.5.10/natspec-format.html).

Also please use OpenZeppelin's solidity-docgen (combined with Gitbooks integration) to generate the initial docs from the comments you add in the contract and then PR.

Also please note only the contracts in the `contracts` folder are in scope so please ignore the contracts in the `pre-audit-contracts` folder.
