### ISSUE TITLE
Integrate dsproxy 

### ISSUE THREAD

**Issue by terminator0x** [plexus-money/contracts#21]
**Problem**

Currently users interact with the plexus contracts using Externally Owned Accounts (EOAs) which is great because it's non-custodial but often leads to a bad UX for complex contract interactions. This especially evident when the user has to approve tokens for use in the yield aggregation process, whereby they have to do multiple approvals depending on the txn being executed.

Having users interact with plexus using EOA's also limit's the number of yield farming operations they can do at a go, because they have to interact with each `tier2...` contract individually which leads to even higher gas costs.

**Solution**

The solution to this is to allow users to use the dsproxy smart contract wallet, which will be deployed once the first time the user interacts with plexus.

After deployment, the dsproxy wallet should now enable the user to interact with multiple functions in different contracts in a single call i.e. they should be able swap ETH for DAI, USDC and USDT, and add liquidity to the ETH/DAI, ETH/USDC and ETH/USDT pools all in a single txn from a single function call.

You can also do some further reading on how the dsproxy works [here](https://ethereum.stackexchange.com/questions/90303/what-is-dsproxy-and-how-does-it-work)

**Acceptance Criteria**

This issue will be deemed solved, if a given account is able to batch add or remove liquidity to multiple pools, all in a single contract call.

Unit tests that `test` this functionality should also be added.

**ETA**

5 days

**Comment by msilucifer** [comment]
Ok. I start this work.
