### ISSUE TITLE
Contracts cleanup and deployment script

### ISSUE THREAD

**Issue by terminator0x** [plexus-money/contracts#22]
**Problem**

The current contracts have a lot of hardcoded token address values, custom interfaces e.t.c and they also use an older version of solidity i.e. v0.7.4. These need to be cleaned up so that the contracts are easy to deploy as possible,

**Solution**

The solutions to the above is the following,

1. Create a custom hardhat script for deployment that'll read the address values  for the various hardcoded tokens & contracts from a `.env` file and pass them to the respective constructors during deployment, so that they are set during deployment.

2. Upgrade the contracts to use the [openzeppelin](https://openzeppelin.com/contracts/) contract interfaces where necessary i.e. like the `PlexusCoin.sol` does.

3.  Upgrade all the contracts to work with solidity versions `pragma solidity >=0.8.0 <0.9.0;`

4. Make sure the deployment works in atleast `rinkeby` or `kovan`

**Acceptance Criteria**

All the tests will still pass without any modifications after the contracts have been updated to work as above.

**ETA**

6 days

**Comment by msilucifer** [comment]
which contract should I cleanup exactly?

**Comment by terminator0x** [comment]
> which contract should I cleanup exactly?

Great question @msilucifer . Please cleanup the contracts in the screenshot, apart from `wrapperBancor.sol`, everything else is in scope.

![Screenshot 2021-06-10 at 7 35 31 PM](https://user-images.githubusercontent.com/78132555/121563562-319d7180-ca23-11eb-99c3-bcdcec42a668.png)

**Comment by msilucifer** [comment]
Thanks, @terminator0x .
So do I need to cleanup a total of 10 contracts?

**Comment by terminator0x** [comment]
> Thanks, @terminator0x .
> So do I need to cleanup a total of 10 contracts?

Yes but you'll find out that there are a lot of repetitions, so most of the work will just be cutting and paste. So plase just take time to go through the contracts so as to optimize your time.

**Comment by msilucifer** [comment]
OK.

**Comment by terminator0x** [comment]
@msilucifer can you please PR what you have done so far, it doesn’t have to be complete. Just want to see progress.

**Comment by msilucifer** [comment]
Please give me the permission for git push.

**Comment by terminator0x** [comment]
> Please give me the permission for git push.

Just make a pull request from your branch to the main branch in this repo so that we review it, no need to git push.
