### ISSUE TITLE
Make sure the contract upgradeability works smoothly in binance and polygon

### ISSUE THREAD

**Issue by terminator0x** [plexus-money/contracts#53]
Contract upgrade-ability  is a core feature of the plexus contracts and it should always work in the mainnet regardless of how many deployments we do.

So for this, create a script called `upgradeChecks.js` in the scripts folder and the script should do the following.

1. Deploy the `tokenrewards.sol` contract and it's proxy to either binance or polygon depending on the `--network` param passed.
2. Re-deploy the contract again to a new address and point to it with the proxy and make sure the variables are still the same.
3. Check that ownership of the contract doesn't change regardless of multiple deploys

The goal of this script is to make sure, aside from the current upgrade-ability hardhat tests, that the contract upgrades functionality **will not break** when released in a live environment with an actual blockchain asides from the current hardhat fork.

The rest of the contract functionality will be tested later in the ETH mainnet when the actual deployment takes place.

**ETA**

1 day

**Comment by terminator0x** [comment]
@softskillpro after merging your commit, I got this build [error](https://github.com/plexus-money/contracts/runs/2990262294?check_suite_focus=true) so please re-check your PR, fix it and rebase against master.

Also why do you have 2 PR's? Just noticing this now.

**Comment by softskillpro** [comment]
@terminator0x 
Sorry, there wasn't "@nomiclabs/hardhat-etherscan" package in package.json?
Also ETHERSCAN_API_KEY in .env
I added etherscan configuration in bellow PR with updated package.json
https://github.com/plexus-money/contracts/pull/50
But this PR is not merged.  so package.json doesn't have
 
 Just pushed again.
