### ISSUE TITLE
Contract cleanup

### ISSUE THREAD

**Issue by terminator0x** [plexus-money/contracts#83]
Please move all the current contracts in the base folder `/contracts` to a new folder called `/wrapper`. So that we'll have 4 folders now inside `/contracts` folder  i.e. `/interfaces`, `/proxyLib`, `/utils`and now `/wrapper`.

The reason for this is, we're going to be adding new contracts soon and it would be great to have this separation to easily understand the code.

Update all tests to work accordingly after moving the contracts.

**ETA**

1 day

**Comment by softskillpro** [comment]
Okay got it.
